// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9icgMYkw_i07maRBGz6txPRTw6BZpNQc',
    appId: '1:781477864703:web:5969924515232eba58d8ca',
    messagingSenderId: '781477864703',
    projectId: 'final-tabib',
    authDomain: 'final-tabib.firebaseapp.com',
    storageBucket: 'final-tabib.firebasestorage.app',
    measurementId: 'G-8JD8VSC5W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKcRtO0wDl3PnUdFl38QHfqKdyNuJLAyQ',
    appId: '1:781477864703:android:1ac4a6823ff14d0658d8ca',
    messagingSenderId: '781477864703',
    projectId: 'final-tabib',
    storageBucket: 'final-tabib.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-5BS7wRuUnwryskFIrt6HDZJdPBiq8ZA',
    appId: '1:781477864703:ios:1214b9043ee8fee958d8ca',
    messagingSenderId: '781477864703',
    projectId: 'final-tabib',
    storageBucket: 'final-tabib.firebasestorage.app',
    iosBundleId: 'com.example.finalTabib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-5BS7wRuUnwryskFIrt6HDZJdPBiq8ZA',
    appId: '1:781477864703:ios:1214b9043ee8fee958d8ca',
    messagingSenderId: '781477864703',
    projectId: 'final-tabib',
    storageBucket: 'final-tabib.firebasestorage.app',
    iosBundleId: 'com.example.finalTabib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9icgMYkw_i07maRBGz6txPRTw6BZpNQc',
    appId: '1:781477864703:web:e95686df98e4fd8658d8ca',
    messagingSenderId: '781477864703',
    projectId: 'final-tabib',
    authDomain: 'final-tabib.firebaseapp.com',
    storageBucket: 'final-tabib.firebasestorage.app',
    measurementId: 'G-SEH86TY7SE',
  );
}
